<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite errors="0" failures="2" hostname="LAPTOP-0P9UAN6J" name="pytest" skipped="0" tests="22" time="0.168"
               timestamp="2022-06-07T06:47:06.890569">
        <testcase classname="test_assert" name="test_add_1" time="0.001"/>
        <testcase classname="test_assert" name="test_add_2" time="0.001"/>
        <testcase classname="test_assert" name="test_add_3" time="0.001"/>
        <testcase classname="test_assert" name="test_add_4" time="0.001"/>
        <testcase classname="test_assert" name="test_in" time="0.001"/>
        <testcase classname="test_assert" name="test_not_in" time="0.001"/>
        <testcase classname="test_assert" name="test_true_1" time="0.001"/>
        <testcase classname="test_assert" name="test_true_2" time="0.001"/>
        <testcase classname="test_assert" name="test_true_3" time="0.001"/>
        <testcase classname="test_assert" name="test_true_4" time="0.001"/>
        <testcase classname="test_assert" name="test_fasle_1" time="0.001"/>
        <testcase classname="test_fail" name="test_fail" time="0.001">
            <failure message="assert (2 + 1) == 4">def test_fail():
                &gt; assert (2 + 1) == 4
                E assert (2 + 1) == 4

                test_fail.py:5: AssertionError
            </failure>
        </testcase>
        <testcase classname="test_fail" name="test_success" time="0.001"/>
        <testcase classname="test_fixtures_01" name="test_multiply_3_4" time="0.002"/>
        <testcase classname="test_fixtures_01" name="test_multiply_a_3" time="0.002"/>
        <testcase classname="test_fixtures_02.TestMultiply" name="test_numbers_5_6" time="0.002"/>
        <testcase classname="test_fixtures_02.TestMultiply" name="test_strings_b_2" time="0.002"/>
        <testcase classname="test_parameterize" name="test_pow[case1]" time="0.001"/>
        <testcase classname="test_parameterize" name="test_pow[case2]" time="0.001"/>
        <testcase classname="test_parameterize" name="test_pow[case3]" time="0.001"/>
        <testcase classname="test_parameterize" name="test_pow[case4]" time="0.001"/>
        <testcase classname="test_sample" name="test_answer" time="0.001">
            <failure message="assert 4 == 5&#10; +  where 4 = inc(3)">def test_answer():
                &gt; assert inc(3) == 5
                E assert 4 == 5
                E + where 4 = inc(3)

                test_sample.py:13: AssertionError
            </failure>
        </testcase>
    </testsuite>
</testsuites>